### ISSUE TITLE
Switch to better filecheck?

### ISSUE THREAD

**Issue by AntonLydike** [KULeuven-MICAS/snax-mlir#171]
hey all, I just so happen to know about a better implementation of the `filecheck` tool that we are using: [AntonLydike/filecheck](https://github.com/AntonLydike/filecheck).

Would be fun to switch, as this would gain us:
- variable capture
- `CHECK-SAME`
- `CHECK-DAG`
- `CHECK-LABEL`

etc...

@jorendumoulin @JosseVanDelm

**Comment by AntonLydike** [comment]
(xDSL is in the process of switching to this as well)

**Comment by jorendumoulin** [comment]
lmao
I remember you ranting about the old tool in Cambridge, you swore you would one day rewrite it :)

Definitely fine to switch for me!
