### ISSUE TITLE
Fix front-end from TFLite flatbuffer to linalg on memrefs

### ISSUE THREAD

**Issue by jorendumoulin** [KULeuven-MICAS/snax-mlir#37]
The quantized MLPerf Tiny models are available as tflite flatbuffers at [their github repo](https://github.com/mlcommons/tiny)

There are still some problems to solve to enable an autometic frontend implementation from tensorflow to lingalg generics on memrefs, to feed into the existing compile chain.

A tensorflow lite model can be exported to MLIR in the `tosa` dialect.

The following piece of code exports an MLIR bytecode file:
(this is the exact same inplementation as in IREE)
```python
import tensorflow as tf
tf.mlir.experimental.tflite_to_tosa_bytecode(
        input_source,
        output_file,
        use_external_constant=False,
        ordered_input_arrays=None,
        ordered_output_arrays=None
    )
```

**Problem 1:** The output bytecode is in bytecode version 1, which is not yet supported by MLIR-16, the version used in the current compiler toolchain:

```
ad01_int8.mlir.bc:0:0: error: bytecode version 1 is newer than the current version 0
```

For now, we can manually circumvent this problem by parsing the bytecode file in a more recent version of MLIR, and then using `tomlir16.py` to create an MLIR-16 compatible file.

Now there remains the lowering to linalg operations and bufferization.

The pass `tosa-to-linalg` sounds promising and can be used with the following command:

```
mlir-opt --pass-pipeline='builtin.module(func.func(tosa-to-linalg))'
```
**Problem 2:** Unfortunately, this throws the following errors:
```
kernels/mnist/mnist_manual.mlir:8:10: error: failed to legalize operation 'tosa.fully_connected'
    %5 = tosa.fully_connected %4, %3, %2 {quantization_info = #tosa.conv_quant<input_zp = -128, weight_zp = 0>} : (tensor<?x784xi8>, tensor<128x784xi8>, tensor<128xi32>) -> tensor<?x128xi32>
         ^
kernels/mnist/mnist_manual.mlir:8:10: note: see current operation: %5 = "tosa.fully_connected"(%4, %3, %2) <{quantization_info = #tosa.conv_quant<input_zp = -128, weight_zp = 0>}> : (tensor<?x784xi8>, tensor<128x784xi8>, tensor<128xi32>) -> tensor<?x128xi32>
```

The following pass does mostly work:

```
mlir-opt --pass-pipeline='builtin.module(func.func(tosa-to-linalg-named, tosa-to-tensor, tosa-to-arith, tosa-to-scf, tosa-to-linalg, tosa-to-arith))'
```

**Problem 3:** However, the `tosa.apply_scale` operation stays unaffected.
```
%21 = tosa.apply_scale %20, %c1205542131_i32, %c38_i8 {double_round = true} : (i32, i32, i8) -> i32
```

So far, I have not found a successful lowering path for the `tosa.apply_scale`.
The following piece of code can be used as a test case:
```
module {
  func.func @mnist() -> i32 {
    %c1205542131_i32 = arith.constant 12468 : i32
    %c38_i8 = arith.constant 38 : i8
    %c12345_i32 = arith.constant 12345 : i32
    %0 = tosa.apply_scale %c12345_i32, %c1205542131_i32, %c38_i8 {double_round = true} : (i32, i32, i8) -> i32
    return %0 : i32
  }
}
```

**Comment by jorendumoulin** [comment]
The `tosa.apply_scale` can be lowered using `--tosa-to-arith="include-apply-rescale"`

**Comment by jorendumoulin** [comment]
**Problem 4: **
All examples that i have checked out use assymetric quantization.
Most quantization frameworks also seem to default to assymetric quantization (https://www.tensorflow.org/model_optimization/guide/quantization/training_example)
When lowering to `linalg`, this results in the usage of the `linalg.quantized_matmul` op:

> linalg.quantized_matmul (linalg::QuantizedMatmulOp)
>
>Performs a matrix multiplication of two 2D inputs.
>
>Numeric casting is performed on the operands to the inner multiply, promoting them to the same data type as the >accumulator/output. The quantized variant includes zero-point adjustments for the left and right operands of the matmul. >Traits: AttrSizedOperandSegments, SingleBlock, SingleBlockImplicitTerminator

The zero-point adjustment is there to support assymetric quantization schemes.
Transforming to linalg generic then looks like this:

```
    %5 = linalg.generic {indexing_maps = [#map3, #map4, #map5, #map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%arg0, %3, %c-128_i32, %c0_i32 : tensor<?x784xi8>, tensor<784x128xi8>, i32, i32) outs(%1 : tensor<?x128xi32>) {
    ^bb0(%in: i8, %in_7: i8, %in_8: i32, %in_9: i32, %out: i32):
      %20 = arith.extsi %in : i8 to i32
      %21 = arith.subi %20, %in_8 : i32
      %22 = arith.extsi %in_7 : i8 to i32
      %23 = arith.subi %22, %in_9 : i32
      %24 = arith.muli %21, %23 : i32
      %25 = arith.addi %out, %24 : i32
      linalg.yield %25 : i32
    } -> tensor<?x128xi32>
```

This kernel includes two additional subtractions for the zero-point correction, which is not supported by our gemm accelerator. The kernel can thus not be matched to the gemm

Solutions

- Include a zero-point adjustment in the accelerator?
- Find models without asymmetric quantization?
- Haul subtraction out of the kernel? (This is very stupid and depressing and won't even work)

**Comment by JosseVanDelm** [comment]
@xiaoling-yi @rgantonio @guilherme-paim

**Comment by xiaoling-yi** [comment]
Hi @jorendumoulin , do you mean the kernel does: C = (A - a) * (B - b), in which a and b is a scalar value? If it is, this is not difficult to implement in the gemm accelerator.

**Comment by jorendumoulin** [comment]
@xiaoling-yi Yes, exactly! I think the best solution is to implement this in hardware as i don't think this comes with a large overhead. I also think this will be a quite common operation, so maybe it is even an idea to implement this in the data streamers discussed on teams last week?

**Comment by xiaoling-yi** [comment]
@jorendumoulin , OK! I then implement C = (A - a) * (B - b) first for our gemm accelerator. But I think it's easier to implement this using CSR to send the a and b values to gemm since how should we implement the streamer still isn't very clear to me now!

**Comment by xiaoling-yi** [comment]
Hi @jorendumoulin , what do you mean " to implement this in the data streamers"? I may not understand clearly haha.
Also, is the a and b 8-bit integers?

**Comment by jorendumoulin** [comment]
Hi @xiaoling-yi

> @jorendumoulin , OK! I then implement C = (A - a) * (B - b) first for our gemm accelerator. But I think it's easier to implement this using CSR to send the a and b values to gemm since how should we implement the streamer still isn't very clear to me now!

I agree with this! The data streamers are still a future project. For now, the best solution is indeed to implement this into GEMM with CSR.

>  Also, is the a and b 8-bit integers?
> @jorendumoulin I'm also a bit confused that the subtraction has to happen in i32, MLIR seems to keep converting the linalg to have this done in 32 bits, can't it do this right before the multiplication instead?

Yes, in MLIR a and b are 32-bit integers. However, I think in almost all cases these values will be smaller than 8-bit. (A - a) would then result in 9-bit values.
